---
parent: "swaggerjson"
name: "SwaggerjsonGetAnonymousInvalid"
description: null
type: "SUITE"
endpoint: "/swaggerJson/"
method: "GET"
auth: "Anonymous"
headers:
- "Accept: application/json"
- "Content-Type: application/json"
testCases: []
assertions:
- "@StatusCode != 200"
tags:
- "V1"
authors:
- "FX Bot"
category: "UnSecured"
severity: "Critical"
inactive: false
policies: null
